Update readme files
MyeongWoonJang/cpp-study pull request #25
Opened 2022-10-03 10:03 UTC by MyeongWoonJang

2022-10-03 10:16 UTC, Lcat12345 reviewed
![image](https://user-images.githubusercontent.com/62102830/193553901-d6bfffa7-d5f5-4925-b27e-22f70ba54891.png)
Comment 로 Submit review 해보기

2022-10-03 10:16 UTC, Lcat12345 commented on readme/branch.md
> +`Branch`가 왜 필요한지, 어떤 기능을 하는지 이 글을 통해 소개하도록 하겠습니다.
테스트 리뷰입니다.

2022-10-03 10:16 UTC, Lcat12345 commented on readme/branch.md
> +  - `팔` 만들기
각 코드에 대해 여러가지 코멘트를 남길 수 있습니다.

2022-10-03 10:18 UTC, Lcat12345 commented on readme/github_desktop_guide.md
> +## Github Desktop 설치하기
새로운 코멘트

2022-10-03 10:19 UTC, Lcat12345 commented on readme/github_desktop_guide.md
> +## Github Desktop 설치하기
Add single comment

2022-10-03 10:22 UTC, Lcat12345 requested changes
여러줄 
테스트

2022-10-03 10:22 UTC, Lcat12345 commented on readme/github_desktop_guide.md
> +<div align="center"><image width="200" height="203" src="https://user-images.githubusercontent.com/73771162/192854338-83686689-1e51-4781-a21d-3f99adfd0471.png"></div>
여러줄 리뷰

2022-10-03 10:23 UTC, Lcat12345 approved these changes

2022-10-04 10:24 UTC, merged

2022-10-06 11:56 UTC, MyeongWoonJang reviewed
리뷰

2022-10-06 11:56 UTC, MyeongWoonJang commented on readme/github_desktop_guide.md
>    - ★ [`Commit`](#commit)
Leave a comment

2022-10-06 11:56 UTC, MyeongWoonJang commented on readme/github_desktop_guide.md
>  - `History` 목록에서 과거 작업 내용을 한 눈에 볼 수 있습니다.
Add review comment

2022-10-06 12:04 UTC, MyeongWoonJang commented on readme/branch.md
> -분기점을 만들어서 독립적인 작업 흐름을 보장하죠.
ㅁㄴ